#!/bin/sh
# mkapk: turn a DESTDIR tree into a signed Alpine .apk, using Alpine's own
# stream tools and apk_tar's exact tar invocation rather than guessing at the
# format.
#
# Runs anywhere `abuild-tar`, `abuild-sign`, `tar`, `gzip` and `openssl` exist
# (abuild-tar only rewrites tar headers, so it is arch independent): packaging
# happens natively in the build container, not in the qemu-emulated chroot.
#
#   mkapk.sh --name thing --version 1.2.3 --destdir build/destdir/thing \
#            --out packages/thing_1.2.3-r0.apk \
#            --key build/keys/solovox-build.rsa --key-name solovox-build.rsa.pub
#
# The three gzip streams and their order are abuild's:
#
#   .SIGN.RSA.<keyname>   RSA-SHA1 over the compressed control stream
#   .PKGINFO              the control stream, its end-of-archive record cut
#   payload               the data stream, hashed per file
#
# Two things are load-bearing, and each was found by testing against apk rather
# than by reading documentation:
#
#   - the tar flags below are apk_tar from abuild's functions.sh. Without
#     `--format=posix --pax-option=exthdr.name=%d/PaxHeaders/%f,atime:=0,ctime:=0`
#     tar writes its own extended-header naming, apk mis-parses the stream and
#     the package is refused with "package file format error" (-1026).
#   - the signature stream has to be there at all: without it apk answers "BAD
#     archive" (-74 EBADMSG), which is the only explanation it gives.
#
# datahash is the sha256 of the *compressed* data stream, as abuild writes it.
set -eu

NAME= VERSION= RELEASE=0 DESTDIR= OUT= KEY= KEY_NAME=
DESCRIPTION= URL= LICENSE= MAINTAINER= PACKAGER=
DEPENDS=
EPOCH="${SOURCE_DATE_EPOCH:-0}"

usage() {
  sed -n '2,32p' "$0" | sed 's/^# \{0,1\}//'
}

while [ $# -gt 0 ]; do
  case "$1" in
    --name) NAME=$2; shift 2 ;;
    --version) VERSION=$2; shift 2 ;;
    --release) RELEASE=$2; shift 2 ;;
    --destdir) DESTDIR=$2; shift 2 ;;
    --out) OUT=$2; shift 2 ;;
    --key) KEY=$2; shift 2 ;;
    --key-name) KEY_NAME=$2; shift 2 ;;
    --description) DESCRIPTION=$2; shift 2 ;;
    --url) URL=$2; shift 2 ;;
    --license) LICENSE=$2; shift 2 ;;
    --maintainer) MAINTAINER=$2; shift 2 ;;
    --packager) PACKAGER=$2; shift 2 ;;
    --depend) DEPENDS="$DEPENDS $2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "mkapk: unknown option: $1" >&2; exit 1 ;;
  esac
done

for v in NAME VERSION DESTDIR OUT KEY KEY_NAME; do
  eval "[ -n \"\$$v\" ]" || { echo "mkapk: --$(echo "$v" | tr 'A-Z' 'a-z' | tr '_' '-') is required" >&2; exit 1; }
done
[ -d "$DESTDIR" ] || { echo "mkapk: no such destdir: $DESTDIR" >&2; exit 1; }
for tool in abuild-tar abuild-sign tar gzip sha256sum openssl; do
  command -v "$tool" >/dev/null 2>&1 || { echo "mkapk: $tool not found (install abuild)" >&2; exit 1; }
done

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# apk_tar, copied from /usr/share/abuild/functions.sh. Names arrive on stdin, NUL
# separated and already expanded (--no-recursion).
apk_tar() {
  tar --format=posix \
    --pax-option=exthdr.name=%d/PaxHeaders/%f,atime:=0,ctime:=0 \
    --no-recursion --null -f - -c --mtime="@$EPOCH" \
    --owner=0 --group=0 --numeric-owner -T -
}

# --- data stream ------------------------------------------------------------
# `find "$@"` (not `find .`) so member names carry no leading "./", which is how
# abuild's data tars look.
(
  cd "$DESTDIR"
  set -- *
  if [ "$1" = "*" ]; then
    echo "mkapk: $DESTDIR is empty" >&2
    exit 1
  fi
  find "$@" -print0 | LC_ALL=C sort -z | apk_tar | abuild-tar --hash | gzip -n -9
) > "$work/data.tar.gz" || exit 1

DATAHASH=$(sha256sum "$work/data.tar.gz" | cut -f1 -d' ')
# busybox find has no -printf, and this runs in an Alpine container
SIZE=$(find "$DESTDIR" -type f -exec stat -c '%s' {} + | awk '{ s += $1 } END { print s + 0 }')

# --- control stream ---------------------------------------------------------
mkdir -p "$work/control"
{
  echo "# Generated by tools/mkapk.sh from a recipe build"
  echo "pkgname = $NAME"
  echo "pkgver = $VERSION-r$RELEASE"
  [ -n "$DESCRIPTION" ] && echo "pkgdesc = $DESCRIPTION"
  [ -n "$URL" ] && echo "url = $URL"
  echo "builddate = $EPOCH"
  echo "packager = ${PACKAGER:-Unknown}"
  echo "size = $SIZE"
  echo "arch = aarch64"
  echo "origin = $NAME"
  [ -n "$MAINTAINER" ] && echo "maintainer = $MAINTAINER"
  [ -n "$LICENSE" ] && echo "license = $LICENSE"
  for dep in $DEPENDS; do
    echo "depend = $dep"
  done
  echo "datahash = $DATAHASH"
} > "$work/control/.PKGINFO"

(
  cd "$work/control"
  # --cut drops the end-of-archive record, as abuild does for the control stream
  printf '.PKGINFO\0' | apk_tar | abuild-tar --cut | gzip -n -9
) > "$work/control.tar.gz" || exit 1

# --- signature and assembly -------------------------------------------------
# abuild-sign rewrites control.tar.gz in place: the signature member becomes the
# first stream of that file, which is the order apk expects.
abuild-sign -q -k "$KEY" -p "$(basename "$KEY_NAME")" "$work/control.tar.gz" \
  || { echo "mkapk: abuild-sign failed with key $KEY" >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"
cat "$work/control.tar.gz" "$work/data.tar.gz" > "$OUT"

files=$(find "$DESTDIR" -type f | wc -l)
echo "$OUT: $NAME-$VERSION-r$RELEASE aarch64, $files file(s), $SIZE bytes installed, $(wc -c < "$OUT") bytes packed, signed with $(basename "$KEY")"
